name: Run tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  test:
    permissions:
      id-token: write

    uses: FasterSpeeding/Piped/.github/workflows/py-test.yml@f20a1d60900d648fb6f1e4e95460288920c4f17f
    secrets: inherit
    with:
      os-versions: '["ubuntu-latest", "macos-latest", "windows-latest"]'
      python-versions: '["3.11", "3.12", "3.13", "3.14"]'
