name: Run tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  test:
    permissions:
      id-token: write

    uses: FasterSpeeding/Piped/.github/workflows/py-test.yml@139f1cf2c740f798a6a8c392b26f84c1ae13a7ac
    secrets: inherit
    with:
      os-versions: '["ubuntu-latest", "macos-latest", "windows-latest"]'
      python-versions: '["3.11", "3.12", "3.13", "3.14-dev"]'
