name: Publish documentation

on:
  workflow_call:
  release:
    # Only use the types keyword to narrow down the activity types that will trigger your workflow.
    types:
      - published

jobs:
  publish-docs:
    uses: FasterSpeeding/Piped/.github/workflows/release-docs.yml@f20a1d60900d648fb6f1e4e95460288920c4f17f
    secrets: inherit
