name: Type check

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  type-check:
    uses: FasterSpeeding/Piped/.github/workflows/type-check.yml@f20a1d60900d648fb6f1e4e95460288920c4f17f
